version: '3'
services:

  seed:
    image: shopping-cart:0.1.0
    expose:
    - 1600
    environment:
      JAVA_OPTS: "-Dconfig.resource=cluster-application-docker.conf"
      CLUSTER_IP: seed
      CLUSTER_PORT: 1600
      SEED_PORT_1600_TCP_ADDR: seed
      CASSANDRA_CONTACT_POINT1: cassandra-db
      CINNAMON_ELASTIC_HOSTS: elasticsearch:9200
    networks:
    - statepoc

  cluster:
    image: shopping-cart:0.1.0
    environment:
      JAVA_OPTS: "-Dconfig.resource=cluster-application-docker.conf"
      CLUSTER_IP: cluster
      CLUSTER_PORT: 0
      SEED_PORT_1600_TCP_ADDR: seed
      CASSANDRA_CONTACT_POINT1: cassandra-db
      CINNAMON_ELASTIC_HOSTS: elasticsearch:9200
    networks:
    - statepoc

  endpoint:
    image: shopping-cart:0.1.0
    environment:
      JAVA_OPTS: "-Dconfig.resource=endpoint-application-docker.conf"
      CLUSTER_IP: endpoint
      CLUSTER_PORT: 0
      SEED_PORT_1600_TCP_ADDR: seed
      CINNAMON_ELASTIC_HOSTS: elasticsearch:9200
    depends_on:
    - seed
    ports:
    - "8082:8082"
    - "8558:8558"
    networks:
    - statepoc

networks:
  statepoc:
    driver: bridge
