version: '3'
services:

  cassandra:
    image: cassandra:latest
    expose:
      - 9042

  seed:
    image: shopping-cart:0.1.0
    expose:
    - 1600
    environment:
      JAVA_OPTS: "-Dconfig.resource=cluster-application-docker.conf"
      CLUSTER_IP: seed
      SEED_HOST: seed
      CASSANDRA_CONTACT_POINT: cassandra:9042

  cluster:
    image: shopping-cart:0.1.0
    environment:
      JAVA_OPTS: "-Dconfig.resource=cluster-application-docker.conf"
      CLUSTER_IP: cluster
      SEED_HOST: seed
      CASSANDRA_CONTACT_POINT: cassandra:9042

  endpoint:
    image: shopping-cart:0.1.0
    environment:
      JAVA_OPTS: "-Dconfig.resource=endpoint-application-docker.conf"
      CLUSTER_IP: endpoint
      SEED_HOST: seed
    depends_on:
    - seed
    ports:
    - "8082:8082"
    - "8558:8558"

networks:
  default:
    external:
      name: statepoc
