version: '3'
services:

  seed:
    image: shopping-cart:0.1.0
    expose:
    - 1600
    environment:
      JAVA_OPTS: "-Dconfig.resource=cluster-application-docker.conf"
      CLUSTER_IP: seed
      CLUSTER_PORT: 1600
      SEED_PORT_1600_TCP_ADDR: seed
      CASSANDRA_CONTACT_POINT: 192.168.16.2:9042

  cluster:
    image: shopping-cart:0.1.0
    environment:
      JAVA_OPTS: "-Dconfig.resource=cluster-application-docker.conf"
      CLUSTER_IP: cluster
      CLUSTER_PORT: 0
      SEED_PORT_1600_TCP_ADDR: seed
      CASSANDRA_CONTACT_POINT: 192.168.16.2:9042

  endpoint:
    image: shopping-cart:0.1.0
    environment:
      JAVA_OPTS: "-Dconfig.resource=endpoint-application-docker.conf"
      CLUSTER_IP: endpoint
      CLUSTER_PORT: 0
      SEED_PORT_1600_TCP_ADDR: seed
    depends_on:
    - seed
    ports:
    - "8082:8082"
    - "8558:8558"

networks:
  default:
    external:
      name: statepoc
