apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 3
  selector:
     matchLabels:
       app: CartCluster
  template:
    metadata:
      labels:
        app: CartCluster
        tag: clusternode
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: nodes-sa
      containers:
      - name: node
        image: gcr.io/project-wuhu/shopping-cart:0.1.0
        env:
        - name: HOSTNAME
          valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        - name: CASSANDRA_CONTACT_POINT
          value: "10.128.0.6:9042"
        - name: JAVA_OPTS
          value: "-Dconfig.resource=cluster-application-k8s.conf"
        ports:
        # akka remoting
        - name: remoting
          containerPort: 2552
          protocol: TCP
        # external http
        - name: akka-mgmt-http
          containerPort: 8558
          protocol: TCP
        - name: node-metrics
          containerPort: 9001
      restartPolicy: Always

